--TEMPLATE--
function one($two = 'three', $four, $five) {
}

--TOKENS--
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "one"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "two"
TEMPURA_LEXER_TOKEN_EQUALS
TEMPURA_LEXER_TOKEN_STRING_LITERAL "three"
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "four"
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "five"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
0 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
	0 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "one";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[3]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "two";
				1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "three";
			}
			1 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "four";
				1 => NULL;
			}
			2 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "five";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[0]: {
		}
	}
}
