--TEMPLATE--
@one
.two
#three

--TOKENS--
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "one"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_CLASS "two"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_ID "three"
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
