--TEMPLATE--
import "one${two}three";

--TOKENS--
TEMPURA_LEXER_TOKEN_KEYWORD_IMPORT
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_STRING_LITERAL "one"
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "two"
TEMPURA_LEXER_TOKEN_STRING_LITERAL "three"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
0 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
	0 => TEMPURA_AST_NODE_TYPE_IMPORT[1]: {
		0 => TEMPURA_AST_NODE_TYPE_STRING_INTERPOLATION_LIST[3]: {
			0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "one";
			1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "two";
				1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
				}
			}
			2 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "three";
		}
	}
}
