--TEMPLATE--
import 'one';

--TOKENS--
TEMPURA_LEXER_TOKEN_KEYWORD_IMPORT
TEMPURA_LEXER_TOKEN_STRING_LITERAL "one"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
0 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
	0 => TEMPURA_AST_NODE_TYPE_IMPORT[1]: {
		0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "one";
	}
}
