--TEMPLATE--
as
default
foreach
function
import

--TOKENS--
TEMPURA_LEXER_TOKEN_KEYWORD_AS
TEMPURA_LEXER_TOKEN_KEYWORD_DEFAULT
TEMPURA_LEXER_TOKEN_KEYWORD_FOREACH
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_KEYWORD_IMPORT
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
