--TEMPLATE--
function func-attr() { @attr: 'val'; }
function func-attr-multi() { @attr1: 'val1'; @attr2: 'val2'; }
function func-text() { 'text'; }
function func-text-multi() { 'text1'; 'text2'; }
function func-element() { div; }
function func-element-multi() { div; div; }

function charset() {
	@charset: 'UTF-8';
}

function head($siteName) {
	meta charset();
	title {
		title();
		$siteName;
	}
}

function template($title) {
	html {
		head head();
		body {
			h1 title();
			div #main main();
			p 'Lorem ipsum dolor sit amet.';
		}
	}
}

function article-url($article) {
	"/articles/$article.id";
}

function article-snippet($article) {
	div .article {
		a {
			@href: article-url($article);
			$article.headline;
			' (';
			article-url($article);
			')';
		}
	}
}

function title() {
	$title;
}

function main() {
	div .article-list {
		foreach ($articles as $article) {
			article-snippet($article);
		}
	}
}

template();

--TOKENS--
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "func-attr"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "attr"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "val"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "func-attr-multi"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "attr1"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "val1"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "attr2"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "val2"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "func-text"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_STRING_LITERAL "text"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "func-text-multi"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_STRING_LITERAL "text1"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "text2"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "func-element"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "func-element-multi"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "charset"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "charset"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "UTF-8"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "head"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "siteName"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "meta"
TEMPURA_LEXER_TOKEN_IDENTIFIER "charset"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "title"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "title"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "siteName"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "template"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "title"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "html"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "head"
TEMPURA_LEXER_TOKEN_IDENTIFIER "head"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "body"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "h1"
TEMPURA_LEXER_TOKEN_IDENTIFIER "title"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_ID "main"
TEMPURA_LEXER_TOKEN_IDENTIFIER "main"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "p"
TEMPURA_LEXER_TOKEN_STRING_LITERAL "Lorem ipsum dolor sit amet."
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "article-url"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_STRING_LITERAL "/articles/"
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "id"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "article-snippet"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_CLASS "article"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "a"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "href"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "article-url"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "headline"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL " ("
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "article-url"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL ")"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "title"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "title"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "main"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_CLASS "article-list"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_KEYWORD_FOREACH
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "articles"
TEMPURA_LEXER_TOKEN_KEYWORD_AS
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "article-snippet"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "article"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_IDENTIFIER "template"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
0 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[14]: {
	0 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "func-attr";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
				0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "attr";
				1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "val";
			}
		}
	}
	1 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "func-attr-multi";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
				0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "attr1";
				1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "val1";
			}
			1 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
				0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "attr2";
				1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "val2";
			}
		}
	}
	2 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "func-text";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "text";
		}
	}
	3 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "func-text-multi";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
			0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "text1";
			1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "text2";
		}
	}
	4 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "func-element";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[0]: {
				}
			}
		}
	}
	5 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "func-element-multi";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[0]: {
				}
			}
			1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[0]: {
				}
			}
		}
	}
	6 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "charset";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
				0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "charset";
				1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "UTF-8";
			}
		}
	}
	7 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "head";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "siteName";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "meta";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
					0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "charset";
						1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[0]: {
						}
					}
				}
			}
			1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "title";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
					0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "title";
						1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[0]: {
						}
					}
					1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
						0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "siteName";
						1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
						}
					}
				}
			}
		}
	}
	8 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "template";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "title";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "html";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "head";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
							0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "head";
								1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[0]: {
								}
							}
						}
					}
					1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "body";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[3]: {
							0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "h1";
								1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
								}
								2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
										0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "title";
										1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[0]: {
										}
									}
								}
							}
							1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
								1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_ID: "main";
								}
								2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
										0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "main";
										1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[0]: {
										}
									}
								}
							}
							2 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "p";
								1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
								}
								2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "Lorem ipsum dolor sit amet.";
								}
							}
						}
					}
				}
			}
		}
	}
	9 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "article-url";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_STRING_INTERPOLATION_LIST[2]: {
				0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "/articles/";
				1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
					0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
					1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[1]: {
						0 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY: "id";
					}
				}
			}
		}
	}
	10 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "article-snippet";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[1]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_CLASS: "article";
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "a";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[5]: {
							0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "href";
								1 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
									0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "article-url";
									1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[1]: {
										0 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
											0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
											1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
											}
										}
									}
								}
							}
							1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
								1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY: "headline";
								}
							}
							2 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: " (";
							3 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "article-url";
								1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
										0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
										1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
										}
									}
								}
							}
							4 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: ")";
						}
					}
				}
			}
		}
	}
	11 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "title";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "title";
				1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
				}
			}
		}
	}
	12 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "main";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[1]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_CLASS: "article-list";
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
					0 => TEMPURA_AST_NODE_TYPE_FOREACH[3]: {
						0 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
							0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "articles";
							1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
							}
						}
						1 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
							0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "article-snippet";
								1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
										0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "article";
										1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	13 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "template";
		1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[0]: {
		}
	}
}
