--TEMPLATE--
function form-item($data-id, $type = 'text', $name) {
	div .form-item {
		@data-id: $data-id;
		input {
			@type: $type;
			@name: $name;
		}
	}
}

function make-data-id($content) {
	"{id:$content}";
}

html {
	head {
		meta @charset: 'UTF-8';
		title 'Hello, World!';
	}
	body {
		@data-js: "${js}x";
		form {
			@method: 'POST';
			@action: 'https://example.com/api/endpoint';
			div .form-items {
				form-item(make-data-id('username'), default, 'username');
				form-item(make-data-id('password'), 'password', 'password');
			}
		}
	}
}

--TOKENS--
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "form-item"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "data-id"
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "type"
TEMPURA_LEXER_TOKEN_EQUALS
TEMPURA_LEXER_TOKEN_STRING_LITERAL "text"
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "name"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_CLASS "form-item"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "data-id"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "data-id"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "input"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "type"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "type"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "name"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "name"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_KEYWORD_FUNCTION
TEMPURA_LEXER_TOKEN_IDENTIFIER "make-data-id"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "content"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_STRING_LITERAL "{id:"
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "content"
TEMPURA_LEXER_TOKEN_STRING_LITERAL "}"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_IDENTIFIER "html"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "head"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "meta"
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "charset"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "UTF-8"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "title"
TEMPURA_LEXER_TOKEN_STRING_LITERAL "Hello, World!"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_IDENTIFIER "body"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "data-js"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "js"
TEMPURA_LEXER_TOKEN_STRING_LITERAL "x"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "form"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "method"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "POST"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_HTML_ATTRIBUTE_NAME "action"
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_STRING_LITERAL "https://example.com/api/endpoint"
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "div"
TEMPURA_LEXER_TOKEN_HTML_SHORTHAND_ATTRIBUTE_CLASS "form-items"
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "form-item"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "make-data-id"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_STRING_LITERAL "username"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_KEYWORD_DEFAULT
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_STRING_LITERAL "username"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_IDENTIFIER "form-item"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_IDENTIFIER "make-data-id"
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_STRING_LITERAL "password"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_STRING_LITERAL "password"
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_STRING_LITERAL "password"
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
0 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[3]: {
	0 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "form-item";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[3]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "data-id";
				1 => NULL;
			}
			1 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "type";
				1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "text";
			}
			2 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "name";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[1]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_CLASS: "form-item";
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
						0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "data-id";
						1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
							0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "data-id";
							1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
							}
						}
					}
					1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "input";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
							0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "type";
								1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
									0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "type";
									1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
									}
								}
							}
							1 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "name";
								1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
									0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "name";
									1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
									}
								}
							}
						}
					}
				}
			}
		}
	}
	1 => TEMPURA_AST_NODE_TYPE_FUNCTION_DECLARATION[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "make-data-id";
		1 => TEMPURA_AST_NODE_TYPE_PARAMETER_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_PARAMETER[2]: {
				0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "content";
				1 => NULL;
			}
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
			0 => TEMPURA_AST_NODE_TYPE_STRING_INTERPOLATION_LIST[3]: {
				0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "{id:";
				1 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
					0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "content";
					1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
					}
				}
				2 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "}";
			}
		}
	}
	2 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
		0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "html";
		1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
		}
		2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
			0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "head";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "meta";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
							0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "charset";
								1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "UTF-8";
							}
						}
					}
					1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "title";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[1]: {
							0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "Hello, World!";
						}
					}
				}
			}
			1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
				0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "body";
				1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
				}
				2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
					0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
						0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "data-js";
						1 => TEMPURA_AST_NODE_TYPE_STRING_INTERPOLATION_LIST[2]: {
							0 => TEMPURA_AST_NODE_TYPE_VARIABLE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_VARIABLE_NAME: "js";
								1 => TEMPURA_AST_NODE_TYPE_VARIABLE_PROPERTY_LIST[0]: {
								}
							}
							1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "x";
						}
					}
					1 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
						0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "form";
						1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[0]: {
						}
						2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[3]: {
							0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "method";
								1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "POST";
							}
							1 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE[2]: {
								0 => TEMPURA_AST_NODE_TYPE_HTML_ATTRIBUTE_NAME: "action";
								1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "https://example.com/api/endpoint";
							}
							2 => TEMPURA_AST_NODE_TYPE_HTML_ELEMENT[3]: {
								0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "div";
								1 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_LIST[1]: {
									0 => TEMPURA_AST_NODE_TYPE_HTML_SHORTHAND_ATTRIBUTE_CLASS: "form-items";
								}
								2 => TEMPURA_AST_NODE_TYPE_STATEMENT_LIST[2]: {
									0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
										0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "form-item";
										1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[3]: {
											0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
												0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "make-data-id";
												1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[1]: {
													0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "username";
												}
											}
											1 => NULL;
											2 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "username";
										}
									}
									1 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
										0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "form-item";
										1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[3]: {
											0 => TEMPURA_AST_NODE_TYPE_FUNCTION_CALL[2]: {
												0 => TEMPURA_AST_NODE_TYPE_IDENTIFIER: "make-data-id";
												1 => TEMPURA_AST_NODE_TYPE_ARGUMENT_LIST[1]: {
													0 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "password";
												}
											}
											1 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "password";
											2 => TEMPURA_AST_NODE_TYPE_STRING_LITERAL: "password";
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
