--TEMPLATE--
{}:,=();

--TOKENS--
TEMPURA_LEXER_TOKEN_BRACE_LEFT
TEMPURA_LEXER_TOKEN_BRACE_RIGHT
TEMPURA_LEXER_TOKEN_COLON
TEMPURA_LEXER_TOKEN_COMMA
TEMPURA_LEXER_TOKEN_EQUALS
TEMPURA_LEXER_TOKEN_PARENTHESIS_LEFT
TEMPURA_LEXER_TOKEN_PARENTHESIS_RIGHT
TEMPURA_LEXER_TOKEN_SEMICOLON
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
