--TEMPLATE--
"$one"
"$two.three"
"$four.five.six"
"$seven.eight.nine.ten"
"$eleven.twelve.thirteen.fourteen.fifteen"

--TOKENS--
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "one"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "two"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "three"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "four"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "five"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "six"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "seven"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "eight"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "nine"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "ten"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_TOKEN_VARIABLE_NAME "eleven"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "twelve"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "thirteen"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "fourteen"
TEMPURA_LEXER_TOKEN_VARIABLE_PROPERTY "fifteen"
TEMPURA_LEXER_TOKEN_DOUBLE_QUOTE
TEMPURA_LEXER_PSEUDOTOKEN_END

--AST--
